# Fly.io configuration for ME_CORE Backend
app = "me-core-backend"
primary_region = "fra"  # Frankfurt (optimal for Europe)
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  # Use the Fly.io optimized Dockerfile without Java dependencies
  dockerfile = "backend/Dockerfile.fly"
  # Ignore detection of package.json etc
  ignorefile = ".flyignore"

[env]
  # Basic configuration
  ENVIRONMENT = "production"
  PYTHON_ENV = "production"
  MONGO_DB_NAME = "marker_engine"
  
  # Feature flags
  ENABLE_METRICS = "false"
  SPARK_NLP_ENABLED = "false"
  
  # Cache configuration
  CACHE_TYPE = "memory"
  CACHE_DEFAULT_TTL = "3600"
  
  # API configuration
  API_HOST = "0.0.0.0"
  API_PORT = "8000"
  
  # Resources path
  DETECTOR_PATH = "/app/resources"
  
  # Fallback database URL for basic deployment (will show warning)
  DATABASE_URL = "mongodb://localhost:27017/test"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    grace_period = "30s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health/live"

# Resource constraints for better stability
[[vm]]
  size = "shared-cpu-1x"
  memory = 512

# Optional: Add secrets for database connections
# Use: fly secrets set DATABASE_URL="mongodb://..."
# secrets = ["DATABASE_URL"]

# Optional: persistent storage if needed later
# [mounts]
#   source = "data"
#   destination = "/data"