# Nixpacks configuration for Railway
# This helps Railway understand how to build our services

[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"

[deploy]
healthcheckPath = "/api/health/live"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3