# Nixpacks configuration for Railway
# This helps Railway understand how to build our backend service

[variables]
PYTHONPATH = "/app"

[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "openjdk11"]

[phases.install]
cmds = ["pip install -r backend/requirements-base.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "./start-backend.sh"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3