global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'me-core-monitor'
    environment: 'production'

rule_files:
  - "rules/*.yml"

scrape_configs:
  # Backend API metrics
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 10s

  # Spark metrics (if available)
  - job_name: 'spark'
    static_configs:
      - targets: ['spark-nlp:4040']
    metrics_path: '/metrics/json'
    scrape_interval: 30s

  # MongoDB exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093