name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        cd tests/e2e
        npm ci
        
    - name: Install Playwright
      run: |
        cd tests/e2e
        npx playwright install --with-deps
        
    - name: Run E2E tests
      env:
        BASE_URL: ${{ secrets.RAILWAY_BACKEND_URL }}
        API_URL: ${{ secrets.RAILWAY_API_URL }}
      run: |
        cd tests/e2e
        npm run test
        
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: tests/e2e/playwright-report/
        retention-days: 30